export default [
    {name: 'John Doe',  age: 35},
    {name: 'Jane Doe',  age: 32},
    {name: 'Max',       age: 27},
    {name: 'Laura',     age: 28},
    {name: 'Axel',      age: 36},
    {name: 'Mike',      age: 25},
    {name: 'Paul',      age: 31},
    {name: 'Anna',      age: 22},
    {name: 'Laura',     age: 38},
    {name: 'Andy',      age: 29},
    {name: 'John Doe',  age: 35},
    {name: 'Jane Doe',  age: 32},
    {name: 'Max',       age: 27},
    {name: 'Laura',     age: 28},
    {name: 'Axel',      age: 36},
    {name: 'Mike',      age: 25},
    {name: 'Paul',      age: 31},
    {name: 'Anna',      age: 22},
    {name: 'Laura',     age: 38},
    {name: 'Andy',      age: 29},
    {name: 'John Doe',  age: 35},
    {name: 'Jane Doe',  age: 32},
    {name: 'Max',       age: 27},
    {name: 'Laura',     age: 28},
    {name: 'Axel',      age: 36},
    {name: 'Mike',      age: 25},
    {name: 'Paul',      age: 31},
    {name: 'Anna',      age: 22},
    {name: 'Laura',     age: 38},
    {name: 'Andy',      age: 29},
    {name: 'John Doe',  age: 35},
    {name: 'Jane Doe',  age: 32},
    {name: 'Max',       age: 27},
    {name: 'Laura',     age: 28},
    {name: 'Axel',      age: 36},
    {name: 'Mike',      age: 25},
    {name: 'Paul',      age: 31},
    {name: 'Anna',      age: 22},
    {name: 'Laura',     age: 38},
    {name: 'Andy',      age: 29},
    {name: 'John Doe',  age: 35},
    {name: 'Jane Doe',  age: 32},
    {name: 'Max',       age: 27},
    {name: 'Laura',     age: 28},
    {name: 'Axel',      age: 36},
    {name: 'Mike',      age: 25},
    {name: 'Paul',      age: 31},
    {name: 'Anna',      age: 22},
    {name: 'Laura',     age: 38},
    {name: 'Andy',      age: 29},
]